accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import TemplateView


urlpatterns=[
	url(r'^$',views.home),
	url('^login/$',views.login),
	url('^logout/$',views.logout),
	url(r'^register/$',views.register_user),
]

django_backend/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from . import views

urlpatterns = [
	url(r'^$',views.home_redirect,name='home_redirect'),
    path('admin/', admin.site.urls),
    url(r'^account/',include('accounts.urls')),
    url(r'^canteen/',include('canteens.urls')),

]

accounts/models.py
from django.db import models
from random import choice
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    address = models.CharField(_('Address'), max_length=50, blank=True, null=True)
    token = models.CharField(_('Token'), max_length=15, unique=True, db_index=True, null=True)
    subscribed = models.CharField(_('Subscribed or not'), max_length=2, blank=True, null=True)
    collegeid=models.CharField(_('collegeId'), max_length=16, blank=True, null=True,unique=True)
    def set_token(self):
	    self.token = ''.join([choice('abcdefghijklmnopqrstuvwxyz0123456789') for i in range(15)])

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        self.set_token()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from accounts.models import Profile
from django.utils.translation import ugettext_lazy as _



class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = [ 'password', 'username', 'first_name','last_name','email','confirm_password']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    def save(self, commit=True):
   	    user = super(RegisterForm, self).save(commit=False)
   	    user.set_password(self.cleaned_data["password"])
   	    if commit:
             user.save()
   	    return user

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['address','collegeid']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['address'].required = True
        self.fields['collegeid'].required = True
        

accounts/views.py
from django.shortcuts import render
from . import forms
from accounts.forms import RegisterForm,ProfileForm
from django.http import HttpResponse
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail,EmailMessage
from django.template.loader import render_to_string,get_template
from django.utils.html import strip_tags
from django.template import Context
# Create your views here.
def home(request):
	value=request.GET.get('items')
	price=request.GET.get('total')

	# value=request.POST['items']
	# price=request.POST['total']
	# print("value="+value)
	# print(price)
	if value is not None and price is not None:
		# msg=EmailMessage('Request Callback',
  #                      #'Here is the message.', to=['mailme.bidyadhar123@gmail.com'])
		# msg.send()
		array=value.splitlines();
		gbnc=""
		nc8b=""
		nc3b=""
		nc7b=""
		for val in array:
			if "Girls Block NC" in val:
				gbnc+=val
				gbnc+='\n'
			elif "3rd Block NC" in val:
				nc3b+=val
				nc3b+='\n'
			elif "8th Block NC" in val:
				nc8b+=val
				nc8b+='\n'
			elif "7th Block NC" in val:
				nc7b+=val
				nc7b+='\n'
		if gbnc != "":
			temp=gbnc.splitlines()

			gbnc_tot=0
			for val in temp:
				gbnc_tot+=int(val.split(',')[1])*int(val.split(',')[2])
			#temp.append(gbnc_tot)
			print(temp)
			item=[]
			price=[]
			quant=[]
			name=[]
			prods=[]
			for i in temp:
				l=i.split(",")
				item.append(l[0])
				price.append(l[2])
				quant.append(l[1])
				name.append(l[3])
				prods.append([l[0],l[1],l[2],l[3]])
			#return render(request,'accounts/email.html', {'prods':prods,'price':price,'quant':quant,'name':name,'total':gbnc_tot,"user":request.user})

			#html_message=get_template('accounts/email.html').render(Context(prods))
			html_message = render_to_string('accounts/email.html', {'prods':prods,'item':item,'price':price,'quant':quant,'name':name,'total':gbnc_tot,"user":request.user})
			#plain_message = strip_tags(html_message)
			plain_message=render_to_string('accounts/email.txt', {'prods': prods})
			s=""
			for val in temp:
				if type(val) is int:
					s+=str(val)+'\n'
				else:
					s+=val+'\n'
			#print(s)
			send_mail("GBNC ORDER", s, settings.EMAIL_HOST_USER, ["mailme.bidyadhar123@gmail.com"],html_message=html_message)

		if nc8b != "":
			temp=nc8b.splitlines()
			nc8b_tot=0
			for val in temp:
				nc8b_tot+=int(val.split(',')[1])*int(val.split(',')[2])
			#temp.append(nc8b_tot)
			print(temp)
			item=[]
			price=[]
			quant=[]
			name=[]
			prods=[]
			for i in temp:
				l=i.split(",")
				item.append(l[0])
				price.append(l[2])
				quant.append(l[1])
				name.append(l[3])
				prods.append([l[0],l[1],l[2],l[3]])
			#return render(request,'accounts/email.html', {'prods':prods,'price':price,'quant':quant,'name':name,'total':gbnc_tot})

			html_message = render_to_string('accounts/email.html', {'prods':prods,'item':item,'price':price,'quant':quant,'name':name,'total':nc8b_tot,"user":request.user})
			plain_message = strip_tags(html_message)
			# s=""
			# for val in temp:
			# 	if type(val) is int:
			# 		s+=str(val)+'\n'
			# 	else:
			# 		s+=val+'\n'
			#print(s)
			send_mail("8th Block NC ORDER", plain_message, settings.EMAIL_HOST_USER, ["mailme.bidyadhar123@gmail.com"],html_message=html_message)

		if nc7b != "":
			temp=nc7b.splitlines()
			nc7b_tot=0
			for val in temp:
				nc7b_tot+=int(val.split(',')[1])*int(val.split(',')[2])
			#temp.append(nc7b_tot)
			print(temp)
			item=[]
			price=[]
			quant=[]
			name=[]
			prods=[]
			for i in temp:
				l=i.split(",")
				item.append(l[0])
				price.append(l[2])
				quant.append(l[1])
				name.append(l[3])
				prods.append([l[0],l[1],l[2],l[3]])
			#return render(request,'accounts/email.html', {'prods':prods,'price':price,'quant':quant,'name':name,'total':gbnc_tot})

			html_message = render_to_string('accounts/email.html', {'prods':prods,'item':item,'price':price,'quant':quant,'name':name,'total':nc7b_tot,"user":request.user})
			plain_message = strip_tags(html_message)
			# s=""
			# for val in temp:
			# 	if type(val) is int:
			# 		s+=str(val)+'\n'
			# 	else:
			# 		s+=val+'\n'
			#print(s)
			send_mail("7th Block NC ORDER", plain_message, settings.EMAIL_HOST_USER, ["mailme.bidyadhar123@gmail.com"],html_message=html_message)

		if nc3b != "":
			temp=nc3b.splitlines()
			nc3b_tot=0
			for val in temp:
				nc3b_tot+=int(val.split(',')[1])*int(val.split(',')[2])
			#temp.append(nc3b_tot)
			print(temp)
			item=[]
			price=[]
			quant=[]
			name=[]
			prods=[]
			for i in temp:
				l=i.split(",")
				item.append(l[0])
				price.append(l[2])
				quant.append(l[1])
				name.append(l[3])
				prods.append([l[0],l[1],l[2],l[3]])
			#return render(request,'accounts/email.html', {'prods':prods,'price':price,'quant':quant,'name':name,'total':gbnc_tot})

			html_message = render_to_string('accounts/email.html', {'prods':prods,'item':item,'price':price,'quant':quant,'name':name,'total':nc3b_tot,"user":request.user})
			plain_message = strip_tags(html_message)
			# s=""
			# for val in temp:
			# 	if type(val) is int:
			# 		s+=str(val)+'\n'
			# 	else:
			# 		s+=val+'\n'
			#print(s)
			send_mail("3rd Block ORDER", plain_message, settings.EMAIL_HOST_USER, ["mailme.bidyadhar123@gmail.com"],html_message=html_message)


		

		##send_mail("subject", value+price, settings.EMAIL_HOST_USER, ["mailme.bidyadhar123@gmail.com"],fail_silently=False)
	return render(request,'accounts/index.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            print("success")
            # Redirect to a success page?
            return HttpResponseRedirect('/account/')
        else:
            print("failed")
            context = {'error': 'Wrong credintials'}  # to display error?
            return render(request, 'accounts/login.html', {'context': context})
    else:
        context = ''
        return render(request, 'accounts/login.html', {'context': context})

def register_user(request):
	if request.method == 'POST':
		register = RegisterForm(request.POST, prefix='register')
		usrprofile = ProfileForm(request.POST, prefix='profile')
		print(register.is_valid(),register.errors)
		print(usrprofile.is_valid())
		if register.is_valid() * usrprofile.is_valid():
		    user = register.save()
		    usrprof = usrprofile.save(commit=False)
		    usrprof.user = user
		    usrprof.set_token()
		    usrprof.subscribed = '1'
		    usrprof.save()
		    return HttpResponseRedirect('/account/')
		else:
		    messages.info(request, 'Password do not match!')
		    userform = RegisterForm(prefix='register')
		    userprofileform = ProfileForm(prefix='profile')
		    #return HttpResponse('errors')
		    return render(request, 'accounts/register.html', {'messages': messages.get_messages(request),'userform': userform, 'userprofileform': userprofileform})
	else:
	    userform = RegisterForm(prefix='register')
	    userprofileform = ProfileForm(prefix='profile')
	    return render(request, 'accounts/register.html', {'userform': userform, 'userprofileform': userprofileform})

def logout(request):
	##send_mail("subject", "value+price", settings.EMAIL_HOST_USER, ["mailme.bidyadhar123@gmail.com"],fail_silently=False)
	auth_logout(request)
	return HttpResponseRedirect('/account/')

accounts/templates/accounts/email.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<table height="100%" width="100%" border="1" style="border-collapse: collapse;">
		
		<tr>
			<th colspan="2" align="center">User Name:</th>
			<td colspan="2" align="center">{{user.username}}</td>
		</tr>
		<tr>
			<th  colspan="2" align="center">User Email:</th>
			<td colspan="2" align="center">{{user.email}}</td>
		</tr>
		<tr>
			<th colspan="2" align="center">Address:</th>
			<td colspan="2" align="center">{{ user.profile.address }}</td>
    		
		</tr>

		<tr>
			<th colspan="2" align="center">College ID:</th>
			<td colspan="2" align="center">{{user.profile.collegeid}}</td>
		</tr>
		<tr>
			<th align="center">Item Name</th>
			<th align="center">Item Quantity</th>
			<th align="center">Cost</th>
			<th align="center">Canteen Name</th>
		</tr>
			{% for prod in prods %}
       			<tr>
       				{% for des in prod %}
           			<td align="center">{{des}}</td>
           			{% endfor %}
       			</tr>
   			{% endfor %}
		
	</table>
</body>
</html>

accounts/templates/accounts/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>NITK NIGHT CANTEEN</title>
<link href="{% static "accounts/css/bootstrap.css" %}" rel='stylesheet' type='text/css' />
<script src="{% static "accounts/js/jquery.min.js" %}"></script>
<link href="{% static "accounts/css/style.css" %}" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Lobster+Two:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<script src="{% static "accounts/js/wow.min.js" %}"></script>
<link href="{% static "accounts/css/animate.css" %}" rel='stylesheet' type='text/css' />

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script>
	new WOW().init();
</script>
<script src="{% static "accounts/js/simpleCart.js" %}"> </script>	
<script type="text/javascript" src="{% static "accounts/js/move-top.js" %}"></script>
<script type="text/javascript" src="{% static "accounts/js/easing.js" %}"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
				});
			});
</script>
<script type="text/javascript">
	function cycleBackgrounds() {
    var index = 0;
 
    $imageEls = $('.container1 .slide'); // Get the images to be cycled.
 
    setInterval(function () {
        // Get the next index.  If at end, restart to the beginning.
        index = index + 1 < $imageEls.length ? index + 1 : 0;
        
        // Show the next
        $imageEls.eq(index).addClass('show');
        
        // Hide the previous
        $imageEls.eq(index - 1).removeClass('show');
    }, 2000);
};
 
// Document Ready.
$(function () {
    cycleBackgrounds();
});
</script>
</head>
<body>
    
	<div class="header">
		<div class="container">
			<div class="top-header">
				<div class="logo">
					<a href="/account/"><img src="{% static "accounts/images/nitk.png" %}" class="img-responsive" alt="" /></a>
				</div>
				<div class="queries">
					<p>Availability of food
 is restricted to Timings:<span>7pm-2am</span><label></label></p>

				</div>
				<div class="header-right">
						{% if user.is_authenticated %}
						<div class="cart box_1">
							<a href="/canteen/checkout">
								<h3> <span class="simpleCart_total">₹0.00 </span> (<span id="simpleCart_quantity" class="simpleCart_quantity"> 0 </span> items)<img src="{% static "accounts/images/bag.png" %}" alt=""></h3>
							</a>	
							<p><a href="javascript:;" class="simpleCart_empty">Empty card</a></p>
							<div class="clearfix"> </div>
						</div>
						{%endif%}
					</div>
				<div class="clearfix"></div>
			</div>
		</div>
			<div class="menu-bar">
			<div class="container">
				<div class="top-menu">
					<ul>
						<li><a href="/account/" class="scroll">Home</a></li>|
						<li><a href="/canteen/">Night canteens</a></li>|
					
						<div class="clearfix"></div>
					</ul>
				</div>
				{% if not user.is_authenticated %}
				<div class="login-section">
					<ul>
						<li><a href="/account/login">Login</a>  </li> |
						<li><a href="/account/register">Sign Up</a> </li> |
					
						<div class="clearfix"></div>
					</ul>
				</div>
				{%endif%}
				{% if user.is_authenticated %}
				<div class="login-section">
					<ul>
						<li><a href="#">Hello {{request.user.username}}</a>  </li> |
						<li><a href="/account/logout">Sign Out</a> </li> |
					
						<div class="clearfix"></div>
					</ul>
				</div>
				{%endif%}
				<div class="clearfix"></div>
			</div>
		</div>
		
		    <div class="container1">
				
 
    			<div class="slide show" style="background: url({% static "accounts/banner.jpg" %}) no-repeat;"></div>
    			<div class="slide" style="background: url({% static "accounts/banner1.jpg" %}) no-repeat;"></div>
    			<div class="slide" style="background: url({% static "accounts/banner2.jpeg" %}) no-repeat;"></div>
    			<div class="slide" style="background: url({% static "accounts/banner4.jpg" %}) no-repeat;"></div>
			</div>
		
	</div>
	
	<div class="content">
		<div class="ordering-section" id="Order">
			<div class="container">
				<div class="ordering-section-head text-center wow bounceInRight" data-wow-delay="0.4s">
					<h3>Ordering food was never so easy</h3>
					<div class="dotted-line">
						<h4>Just 4 steps to follow </h4>
					</div>
				</div>
				<div class="ordering-section-grids">
					<div class="col-md-3 ordering-section-grid">
						<div class="ordering-section-grid-process wow fadeInRight" data-wow-delay="0.4s"">
							<i class="one"></i><br>
							<i class="one-icon"></i>
							<p>Choose <span>NightCanteen</span></p>
							<label></label>
						</div>
					</div>
					<div class="col-md-3 ordering-section-grid">
						<div class="ordering-section-grid-process wow fadeInRight" data-wow-delay="0.4s"">
							<i class="two"></i><br>
							<i class="two-icon"></i>
							<p>Order  <span>Your Food</span></p>
							<label></label>
						</div>
					</div>
					<div class="col-md-3 ordering-section-grid">
						<div class="ordering-section-grid-process wow fadeInRight" data-wow-delay="0.4s"">
							<i class="three"></i><br>
							<i class="three-icon"></i>
							<p>Pay   <span>on delivery</span></p>
							<label></label>
						</div>
					</div>
					<div class="col-md-3 ordering-section-grid">
						<div class="ordering-section-grid-process wow fadeInRight" data-wow-delay="0.4s"">
							<i class="four"></i><br>
							<i class="four-icon"></i>
							<p>Enjoy <span>your food </span></p>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		
	</div>
	

</body>
</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>NITK NIGHT CANTEEN</title>
<link href="{% static "accounts/css/bootstrap.css" %}" rel='stylesheet' type='text/css' />
<script src="{% static "accounts/js/jquery.min.js" %}"></script>
<link href="{% static "accounts/css/style.css" %}" rel="stylesheet" type="text/css" media="all" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900,200italic,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Lobster+Two:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<script src="{% static "accounts/js/wow.min.js" %}"></script>
<link href="{% static "accounts/css/animate.css" %}" rel='stylesheet' type='text/css' />

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<script>
	new WOW().init();
</script>
<script src="{% static "accounts/js/simpleCart.js" %}"> </script>	
<script type="text/javascript" src="{% static "accounts/js/move-top.js" %}"></script>
<script type="text/javascript" src="{% static "accounts/js/easing.js" %}"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
				});
			});
</script>	
</head>
<body>
  
	<div class="header">
		<div class="container">
			<div class="top-header">
				<div class="logo">
					<a href="/account/"><img src="{% static "accounts/images/nitk.png" %}" class="img-responsive" alt="" /></a>
				</div>
				<div class="queries" align="right">
					<p >Availability of food is restricted to Timings:<span>7pm-2am</span><label></label></p>
				</div>
				<div class="header-right">
						{% if user.is_authenticated %}
						<div class="cart box_1">
							<a href="/canteen/checkout">
								<h3> <span class="simpleCart_total">₹0.00 </span> (<span id="simpleCart_quantity" class="simpleCart_quantity"> 0 </span> items)<img src="{% static "accounts/images/bag.png" %}" alt=""></h3>
							</a>	
							<p><a href="javascript:;" class="simpleCart_empty">Empty card</a></p>
							<div class="clearfix"> </div>
						</div>
						{%endif%}
					</div>
				<div class="clearfix"></div>
			</div>
		</div>
			<div class="menu-bar">
			<div class="container">
				<div class="top-menu">
					<ul>
						<li ><a href="/account/" class="scroll">Home</a></li>|
						<li><a href="/canteen/">Night canteens</a></li>|
					
						<div class="clearfix"></div>
					</ul>
				</div>
				{% if not user.is_authenticated %}
				<div class="login-section">
					<ul>
						<li><a href="/account/login">Login</a>  </li> |
						<li><a href="/account/register">Sign Up</a> </li> |
					
						<div class="clearfix"></div>
					</ul>
				</div>
				{%endif%}
				{% if user.is_authenticated %}
				<div class="login-section">
					<ul>
						<li><a href="/account/login">Hello {{request.user.username}}</a>  </li> |
						<li><a href="/account/logout">Sign Out</a> </li> |
					
						<div class="clearfix"></div>
					</ul>
				</div>
				{%endif%}
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	
	<div class="content">
	<div class="main">
	   <div class="container">
		  <div class="register">
		  	  <form action="" method="post">
				
				<div class="register-top-grid">
				    <h3>PERSONAL INFORMATION</h3>
				    
					<!-- <div class='row'> -->
					    <div class="wow fadeInLeft" data-wow-delay="0.4s">
					        {{ userform.username.errors }}
					        <label for="id_username">Username: </label>
					        {{ userform.username }}
					    </div>
					   
					    
					    
					<!-- </div> -->
					
				    <!-- <div class="row"> -->
					    <div class="wow fadeInLeft" data-wow-delay="0.4s">
					        {{ userform.first_name.errors }}
					        <label for="id_first_name">First name: </label>
					        {{ userform.first_name }}
					    </div>			    
					    <div class="wow fadeInLeft" data-wow-delay="0.4s">
					        {{ userform.last_name.errors }}
					        <label for="id_last_name">Last name: </label>
					        {{ userform.last_name }}
					    </div>
					<!-- </div> -->
				    
					<!-- <div class='row'>  -->   
					    <div class="wow fadeInLeft" data-wow-delay="0.4s">
					        {{ userprofileform.address.errors }}
					        <label for="id_address">Address:</label>
					        {{ userprofileform.address }}
					    </div>
					     
					    <div class="wow fadeInLeft" data-wow-delay="0.4s">
					        {{ userform.email.errors }}
					        <label for="id_email">Email: </label>
					        {{ userform.email }}
					    </div>
					    <div class="wow fadeInLeft" data-wow-delay="0.4s">
					        {{ userprofileform.collegeid.errors }}
					        <label for="id_collegeid">College ID:</label>
					        {{ userprofileform.collegeid }}
					    </div>
					<!-- </div> -->
				</div>
				<div class="clearfix"> </div>
				<div class="register-bottom-grid">
				    <h3>LOGIN INFORMATION</h3>
				    <div class="wow fadeInLeft" data-wow-delay="0.4s">
				        {{ userform.password.errors }}
				        <label for="id_password1">Password: </label>
				        {{ userform.password }}
				    </div>
				    <div class="wow fadeInLeft" data-wow-delay="0.4s">
				        {{ userform.confirm_password.errors }}
				        <label for="id_password2">Confirm Password:</label>
				        {{ userform.confirm_password }}
				    </div>
				</div>
				{% if messages %}
					<ul class="messages">
    				{% for message in messages %}
    					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    				{% endfor %}
					</ul>
				{% endif %}
		    	{% csrf_token %}
			    <div class="register-but">
					   <input type="submit" value="submit">
					   <div class="clearfix"> </div>
				</div>
				
			</form>


		  	  <!-- <form> 
				 <div class="register-top-grid">
					<h3>PERSONAL INFORMATION</h3>
					 <div class="wow fadeInLeft" data-wow-delay="0.4s">
						<span>Name<label>*</label></span>
						<input type="text"> 
					 </div>
					 <div class="wow fadeInRight" data-wow-delay="0.4s">
						<span>College id<label>*</label></span>
						<input type="text"> 
					 </div>
					 <div class="wow fadeInRight" data-wow-delay="0.4s">
						 <span>Email Address<label>*</label></span>
						 <input type="text"> 
					 </div>
					  <div class="wow fadeInRight" data-wow-delay="0.4s">
						 <span>Address<label>*</label></span>
						 <input type="text"> 
					 </div>
					  <div class="wow fadeInRight" data-wow-delay="0.4s">
						 <span>Phone number<label>*</label></span>
						 <input type="text"> 
					 </div>
					</div>
					<div class="clearfix"> </div>
				     <div class="register-bottom-grid">
						    <h3>LOGIN INFORMATION</h3>
							 <div class="wow fadeInLeft" data-wow-delay="0.4s">
								<span>Password<label>*</label></span>
								<input type="password">
							 </div>
							 <div class="wow fadeInRight" data-wow-delay="0.4s">
								<span>Confirm Password<label>*</label></span>
								<input type="password">
							 </div>
					 </div>
				</form> -->
				<div class="clearfix"> </div>
				
		   </div>
	     </div>
	    </div>

<div class="clearfix"></div>
		
	

</body>
</html>